#cloud-config
package_update: true
package_upgrade: true
packages:
  - sshfs
  - build-essential
  - git
  - lynx
  - tmux
  - curl
  - rsync
  - nginx
  - imagemagick
  - pkg-config
  - libxml2-dev
  - libxmlsec1-dev
  - docker.io
  - docker-compose-v2
  - makepasswd
  - shellcheck
  - python3-pip
snap:
  commands:
    - snap install --classic certbot 
groups:
  - docker
  - staff
  - www-data
runcmd:
  - adduser ubuntu docker
  - adduser ubuntu staff
  - adduser ubuntu www-data
  - [ python3, -m, pip, install, invenio-cli, --break-system-packages ]
